- name: Configure server
  hosts: webservers
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt" 
      
    - name: Install Apache
      apt:
        name: apache2
        state: lastest
        update_cache: yes
      when: ansible_pkg_mgr == "apt" 

    - name: Enable Apache
      service:
        name: apache2
        enable: true
        state: started
      when: ansible_pkg_mgr == "apt"